/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseEditCourseIdRouteImport } from './routes/course.edit.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseEditCourseIdRoute = CourseEditCourseIdRouteImport.update({
  id: '/course/edit/$courseId',
  path: '/course/edit/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/course/edit/$courseId': typeof CourseEditCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/course/edit/$courseId': typeof CourseEditCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/course/edit/$courseId': typeof CourseEditCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/course/edit/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/course/edit/$courseId'
  id: '__root__' | '/' | '/course/edit/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseEditCourseIdRoute: typeof CourseEditCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/edit/$courseId': {
      id: '/course/edit/$courseId'
      path: '/course/edit/$courseId'
      fullPath: '/course/edit/$courseId'
      preLoaderRoute: typeof CourseEditCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseEditCourseIdRoute: CourseEditCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
